### ISSUE TITLE
high resource usage in version 2.1

### ISSUE THREAD

**Issue by rwkyyy** [Newsman/WP-Plugin-NewsmanApp#3]
Hello,

After updating to latest version (2.1) noticed a lot of POST requests going to this: /?newsman=getCart.json, this caused a spike in resources and the website to crash(timeout).

To be clear, the resources are plentifull, the only reason why the website crashed is because there were almost **160k** **requests** generated in less than 2h.

Right now the module is disabled.

Here is my config:
`
### WordPress Environment ###

WordPress address (URL):  
Site address (URL): 
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: ro_RO
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.3
PHP Version: 7.4.25
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.12-MariaDB-1:10.5.12+maria~focal
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 223.48MB
Database Data Size: 169.88MB
Database Index Size: 53.60MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 5.98MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.02MB + Index: 5.84MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 4.02MB + Index: 3.08MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_alp_pickup_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aryo_activity_log: Data: 10.02MB + Index: 0.00MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.44MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.28MB + Index: 1.16MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 53.56MB + Index: 19.45MB + Engine InnoDB
wp_posts: Data: 8.44MB + Index: 2.55MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_reviewx_criterias: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_reviewx_process_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_reviewx_reminder_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sameday_awb: Data: 0.28MB + Index: 0.02MB + Engine InnoDB
wp_sameday_locker: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_sameday_package: Data: 6.50MB + Index: 0.00MB + Engine InnoDB
wp_sameday_pickup_point: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sameday_service: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_stock_log: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.44MB + Index: 0.19MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_ro_ro_en_gb: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_trp_gettext_en_gb: Data: 0.45MB + Index: 0.53MB + Engine InnoDB
wp_trp_gettext_ro_ro: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_trp_original_meta: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_trp_original_strings: Data: 3.52MB + Index: 2.52MB + Engine InnoDB
wp_usermeta: Data: 13.52MB + Index: 2.95MB + Engine InnoDB
wp_users: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_vtcrt_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtcrt_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtcrt_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_purchase_log: Data: 17.52MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_purchase_log_product: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_purchase_log_product_rule: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_vtprd_transient_cart_data: Data: 15.02MB + Index: 0.13MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.47MB + Index: 0.48MB + Engine InnoDB
wp_wc_order_stats: Data: 0.25MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.36MB + Index: 0.61MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 5104
custom_css: 2
customize_changeset: 3
inspire_invoice: 1
language_switcher: 4
local-pickup-pro: 9
nav_menu_item: 60
ni-order-status: 1
option-tree: 1
page: 42
polylang_mo: 2
post: 2
postman_sent_mail: 100
product: 459
product_variation: 1781
revision: 335
shop_coupon: 4
shop_order: 2213
shop_order_refund: 18
vtcrt-rule: 1
vtprd-rule: 1
wc_order_email: 1
wc_order_status: 9
woo_product_tab: 4
wpcf7_contact_form: 2
ywar_reviews: 1
ywdpd_discount: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Ajax Cart AutoUpdate for WooCommerce: by taisho – 1.5.5
Activity Log: by Activity Log Team – 2.8.1
Contact Form 7: by Takayuki Miyoshi – 5.5.3
Disable WooCommerce Bloat: by ospiotr – 2.6.1
Duplicate Page: by mndpsingh287 – 4.4.7
Facturare - Persoana Fizica sau Juridica: by George Ciobanu – 1.1.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.7.0
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.9
LibraPay.ro: by LibraPay IT – 1.3.3
Loco Translate: by Tim Whitlock – 2.5.5
MX Woocommerce Local Pickup Extended: by Media X – 1.0
North - Required Plugin: by fuelthemes – 1.4.1
PixelYourSite: by PixelYourSite – 8.2.15
Post SMTP: by Yehuda Hassine – 2.0.23
Product Variation Swatches for Woocommerce: by ThemeHigh – 2.0.6
reSmush.it Image Optimizer: by reSmush.it – 0.4.2
SamedayCourier Shipping: by SamedayCourier – 1.0.29
Rank Math SEO: by Rank Math – 1.0.80
States, Cities, and Places for WooCommerce: by Kingsley Ochu – 1.3.2
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.1.8

Checkout Field Editor for WooCommerce: by ThemeHigh – 1.5.1
Advanced Order Export For WooCommerce: by AlgolPlus – 3.2.2
Product Feed PRO for WooCommerce: by AdTribes.io – 11.1.1
WooCommerce Pixel Manager: by woopt – 1.12.3
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.11.2
WooCommerce Product Tabs: by WP Concern – 2.0.7
WooCommerce: by Automattic – 6.0.0
WP 404 Auto Redirect to Similar Post: by hwk-fr – 1.0.3
WP All Import Pro: by Soflyy – 4.7.1
WP Rocket: by WP Media – 3.10.5.1
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.8
YITH WooCommerce Wishlist: by YITH – 3.4.0

### Inactive Plugins (4) ###

NewsmanApp for Wordpress: by Newsman – 2.1
NewsmanApp Remarketing: by Newsman – 2.1
VarkTech Pricing Deals for WooCommerce: by Vark – 2.0.2.02

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #16 - /magazin/
Cart: #17 - /cos/
Checkout: #18 - /finalizare/
My account: #19 - /contul-meu/
Terms and conditions: #145 - /termeni-conditii/

### Theme ###

Name: Uprise
Version: 1.2.1
Author URL: 
Child Theme: ✔
Parent Theme Name: North
Parent Theme Version: 5.7.4
Parent Theme Author URL:
WooCommerce Support: ✔

### Templates ###

Overrides: north-wp/woocommerce/archive-product.php
north-wp/woocommerce/cart/cart-empty.php
north-wp/woocommerce/cart/cart.php
north-wp/woocommerce/checkout/form-checkout.php
north-wp/woocommerce/checkout/form-coupon.php
north-wp/woocommerce/checkout/form-login.php
north-wp/woocommerce/content-product.php
north-wp/woocommerce/content-single-product.php
uprise/woocommerce/emails/customer-completed-order.php
north-wp/woocommerce/global/wrapper-end.php
north-wp/woocommerce/global/wrapper-start.php
north-wp/woocommerce/loop/loop-end.php
north-wp/woocommerce/loop/loop-start.php
north-wp/woocommerce/myaccount/form-login.php
north-wp/woocommerce/myaccount/navigation.php
north-wp/woocommerce/product-searchform.php
north-wp/woocommerce/single-product/add-to-cart/variable.php
north-wp/woocommerce/single-product/product-image.php
north-wp/woocommerce/single-product/product-thumbnails.php
uprise/woocommerce/single-product/tabs/tabs.php
north-wp/woocommerce/single-product-reviews.php
north-wp/woocommerce/content-product_cat.php

### Action Scheduler ###

Complete: 15,594
Oldest: 2021-12-14 12:49:18 +0000
Newest: 2022-01-06 08:38:57 +0000

### Status report information ###

Generated at: 2022-01-06 10:40:53 +02:00
`

**Comment by lucianfc** [comment]
We updated the source code, optimized the workload on certain operations, it will send the necessary requests only when certain operations occurred and not always like it was.
We suggest updating to 2.2 version

**Comment by rwkyyy** [comment]
@lucianfcorodeanu problem still persists in 2.2.1
https://ibb.co/LQ3QL5n
23k requests in under an hour.

**Comment by dazoot** [comment]
Hi there @rwkyyy can you contact us here https://www.newsman.com/contact so we can get more details ?
Does this getCart request slow down your server ?

**Comment by lucianfc** [comment]
@rwkyyy what is the website (tld) ? the getCart will get called only if users will click on buttons, etc.

**Comment by rwkyyy** [comment]
@dazoot it kills the server, not slow down.
@lucianfcorodeanu etic.ro is the domain; .ro is tld.

from what I've learned debugging this, they (etic.ro) sent a newsletter and visitor came and added a bunch of products tot the cart, causing this wave of POST requests, timeouting to 180s.

**Comment by dazoot** [comment]
@rwkyyy this `getCart` request is just rendering the cart from session to json. It should be fast enough as there is no DB touched. Anyway we are investigating an update to reduce even more the requests to the `cart` data.
